LOAD DATA SET

In [3]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings("ignore")

In [4]:
filename = "/Users/thabisomakhathini/Downloads/Edited compt data .xlsx"

In [5]:
df = pd.read_excel(filename)
df

,BU,Area,WPU,Plantation,Compt,Effective area (ha),0-15%,16-20%,21-35%,36-45%,46-60%,>60%,Soil Erosion Risk
0,MIDLANDS,UMSHWATI,NEW HANOVER,NEWLANDS,B008A,1.1,0.95,0.03,0.02,0.00,0.00,0.0,LOW
1,MIDLANDS,UMSHWATI,NEW HANOVER,NEWLANDS,B008B,1.8,0.89,0.11,0.00,0.00,0.00,0.0,LOW
2,MIDLANDS,UMKHOMAZI,ILOVU,BATCHELOR,A005A,20.5,0.21,0.37,0.39,0.03,0.00,0.0,LOW
3,LOWVELD,UMKHONDO,TOWER FOREST,ANYSSPRUIT,C211,48.9,1.00,0.00,0.00,0.00,0.00,0.0,LOW
4,LOWVELD,UMKHONDO,TOWER FOREST,ANYSSPRUIT,C209,12.4,1.00,0.00,0.00,0.00,0.00,0.0,LOW
...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D004,20.3,0.99,0.01,0.00,0.00,0.00,0.0,LOW
255,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D002,4.8,0.98,0.02,0.00,0.00,0.00,0.0,LOW
256,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D005,10.7,1.00,0.00,0.00,0.00,0.00,0.0,LOW
257,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D006,8.5,0.88,0.04,0.04,0.03,0.01,0.0,LOW
258,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D007B,5.3,0.70,0.07,0.16,0.06,0.01,0.0,LOW

DATA DESCRIPTION

In [9]:
df.describe()

,Effective area (ha),0-15%,16-20%,21-35%,36-45%,46-60%,>60%
count,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000,259.000000
mean,14.328185,0.730734,0.087452,0.122394,0.035483,0.020077,0.003861
std,11.465128,0.337985,0.104750,0.181707,0.072748,0.061958,0.016488
min,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.800000,0.495000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,11.400000,0.940000,0.040000,0.010000,0.000000,0.000000,0.000000
75%,20.000000,1.000000,0.145000,0.210000,0.020000,0.000000,0.000000
max,71.700000,1.000000,0.530000,0.810000,0.360000,0.510000,0.150000

In [10]:
df.insert(13, "Tool", value='Unknown')

In [11]:
print(df)

           BU       Area           WPU   Plantation  Compt  \
0    MIDLANDS   UMSHWATI   NEW HANOVER     NEWLANDS  B008A
1    MIDLANDS   UMSHWATI   NEW HANOVER     NEWLANDS  B008B
2    MIDLANDS  UMKHOMAZI         ILOVU    BATCHELOR  A005A
3     LOWVELD   UMKHONDO  TOWER FOREST   ANYSSPRUIT   C211
4     LOWVELD   UMKHONDO  TOWER FOREST   ANYSSPRUIT   C209
..        ...        ...           ...          ...    ...
254   LOWVELD      DUMBE       MOOLMAN  LANGFONTEIN   D004
255   LOWVELD      DUMBE       MOOLMAN  LANGFONTEIN   D002
256   LOWVELD      DUMBE       MOOLMAN  LANGFONTEIN   D005
257   LOWVELD      DUMBE       MOOLMAN  LANGFONTEIN   D006
258   LOWVELD      DUMBE       MOOLMAN  LANGFONTEIN  D007B

     Effective area (ha)  0-15%  16-20%  21-35%  36-45%  46-60%  >60%  \
0                    1.1   0.95    0.03    0.02    0.00    0.00   0.0
1                    1.8   0.89    0.11    0.00    0.00    0.00   0.0
2                   20.5   0.21    0.37    0.39    0.03    0.00   0.0
3                   48.9   1.00    0.00    0.00    0.00    0.00   0.0
4                   12.4   1.00    0.00    0.00    0.00    0.00   0.0
..                   ...    ...     ...     ...     ...     ...   ...
254                 20.3   0.99    0.01    0.00    0.00    0.00   0.0
255                  4.8   0.98    0.02    0.00    0.00    0.00   0.0
256                 10.7   1.00    0.00    0.00    0.00    0.00   0.0
257                  8.5   0.88    0.04    0.04    0.03    0.01   0.0
258                  5.3   0.70    0.07    0.16    0.06    0.01   0.0

    Soil Erosion Risk     Tool
0                 LOW  Unknown
1                 LOW  Unknown
2                 LOW  Unknown
3                 LOW  Unknown
4                 LOW  Unknown
..                ...      ...
254               LOW  Unknown
255               LOW  Unknown
256               LOW  Unknown
257               LOW  Unknown
258               LOW  Unknown

[259 rows x 14 columns]

In [12]:
conditions = [
    (df['0-15%'] >= 0.80),  # Condition 1
    (df['16-20%'] >= 0.18),   # Condition 2
    (df['36-45%'] >= 0.01),   # Condition 3
    (df['>60%'] >= 0.01)]      # Condition 4

In [14]:
values = [
    "Mechanised (Boom Sprayer)", # Result for Condition 1
    "Manual (Knapsack)", # Result for Condition 2
    "RPAS (Drone)",              # Result for Condition 3
    "RPAS (Drone)"               # Result for Condition 4
]

In [20]:
df['Tool'] = np.select(conditions, values, default='Other/Unspecified')

In [22]:
df

,BU,Area,WPU,Plantation,Compt,Effective area (ha),0-15%,16-20%,21-35%,36-45%,46-60%,>60%,Soil Erosion Risk,Tool
0,MIDLANDS,UMSHWATI,NEW HANOVER,NEWLANDS,B008A,1.1,0.95,0.03,0.02,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
1,MIDLANDS,UMSHWATI,NEW HANOVER,NEWLANDS,B008B,1.8,0.89,0.11,0.00,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
2,MIDLANDS,UMKHOMAZI,ILOVU,BATCHELOR,A005A,20.5,0.21,0.37,0.39,0.03,0.00,0.0,LOW,Manual (Knapsack)
3,LOWVELD,UMKHONDO,TOWER FOREST,ANYSSPRUIT,C211,48.9,1.00,0.00,0.00,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
4,LOWVELD,UMKHONDO,TOWER FOREST,ANYSSPRUIT,C209,12.4,1.00,0.00,0.00,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D004,20.3,0.99,0.01,0.00,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
255,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D002,4.8,0.98,0.02,0.00,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
256,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D005,10.7,1.00,0.00,0.00,0.00,0.00,0.0,LOW,Mechanised (Boom Sprayer)
257,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D006,8.5,0.88,0.04,0.04,0.03,0.01,0.0,LOW,Mechanised (Boom Sprayer)
258,LOWVELD,DUMBE,MOOLMAN,LANGFONTEIN,D007B,5.3,0.70,0.07,0.16,0.06,0.01,0.0,LOW,RPAS (Drone)

In [24]:
df['Tool'].value_counts()

Mechanised (Boom Sprayer)    157
Manual (Knapsack)             51
RPAS (Drone)                  44
Other/Unspecified              7
Name: Tool, dtype: int64

In [28]:
df.to_excel('Compt info 3.xlsx')